site_name: Coello
nav:
  #- Home: index.md 
  - Research: Research.md 
  - Services: Services.md
  - About us: about.md
  - Posts: Posts.md
        ## Doest his even work


theme :
  name: material
  font:
    text: Roboto
  logo: img/logo_final_222.png
  features:
    - header.autohide
    - navigation.tabs
    #- navitagion.sections
    - toc.intergrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - contant.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: deep purple
    - scheme: slate 
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: deep purple    

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Strogow2
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/edum3800
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eduardomedinaoliveira/
  homepage: docs/index.md
#extra_css:

#  - stylesheets/custom.css
